[global]

log_level = 'info'

[mode]

[mode.clients]

enabled = true
refresh = true
misbehaviour = false

[mode.connections]

enabled = true

[mode.channels]
enabled = true

[mode.packets]

enabled = true
clear_interval = 0
clear_on_start = true
tx_confirmation = true
auto_register_counterparty_payee = true

[rest]

enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]

enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'ibc1'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:16657'
grpc_addr = 'http://127.0.0.1:8090'
event_source = { mode = 'push', url = 'ws://127.0.0.1:16657/websocket', batch_delay = '1000ms' }
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'wallet1'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 50507618
gas_price = { price = 0.001, denom = 'stake' }
gas_multiplier = 1.3
max_msg_num = 5
query_packets_chunk_size = 50
max_tx_size = 3097346
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[[chains]]
id = 'ibc2'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
event_source = { mode = 'push', url = 'ws://127.0.0.1:26657/websocket', batch_delay = '1000ms' }
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'wallet1'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 50507618
gas_price = { price = 0.001, denom = 'stake' }
gas_multiplier = 1.3
max_msg_num = 5
query_packets_chunk_size = 50
max_tx_size = 3097346
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
