#!/bin/bash
RELAYER_BINARY=rly
RELAYER_DIRECTORY=./network/relayer
RELAYER_CONFIG_DIR=./network/relayer/config
PATH_NAME=quicksilver1-stargaze1
CHAIN1=quicksilver-1
CHAIN2=stargaze-1
KEY1=testkey
KEY2=testkey